// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1beta1ProofOps v1beta1 proof ops
//
// swagger:model v1beta1.ProofOps
type V1beta1ProofOps struct {

	// ops
	Ops []*V1beta1ProofOpsOpsItems0 `json:"ops"`
}

// Validate validates this v1beta1 proof ops
func (m *V1beta1ProofOps) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1ProofOps) validateOps(formats strfmt.Registry) error {
	if swag.IsZero(m.Ops) { // not required
		return nil
	}

	for i := 0; i < len(m.Ops); i++ {
		if swag.IsZero(m.Ops[i]) { // not required
			continue
		}

		if m.Ops[i] != nil {
			if err := m.Ops[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ops" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ops" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this v1beta1 proof ops based on the context it is used
func (m *V1beta1ProofOps) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateOps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1beta1ProofOps) contextValidateOps(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Ops); i++ {

		if m.Ops[i] != nil {

			if swag.IsZero(m.Ops[i]) { // not required
				return nil
			}

			if err := m.Ops[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ops" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ops" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1ProofOps) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1ProofOps) UnmarshalBinary(b []byte) error {
	var res V1beta1ProofOps
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// V1beta1ProofOpsOpsItems0 v1beta1 proof ops ops items0
//
// swagger:model V1beta1ProofOpsOpsItems0
type V1beta1ProofOpsOpsItems0 struct {

	// data
	// Format: byte
	Data strfmt.Base64 `json:"data,omitempty"`

	// key
	// Format: byte
	Key strfmt.Base64 `json:"key,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this v1beta1 proof ops ops items0
func (m *V1beta1ProofOpsOpsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this v1beta1 proof ops ops items0 based on context it is used
func (m *V1beta1ProofOpsOpsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1beta1ProofOpsOpsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1beta1ProofOpsOpsItems0) UnmarshalBinary(b []byte) error {
	var res V1beta1ProofOpsOpsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
