services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - IN_DOCKER_TARGET=fail
    volumes:
      - type: bind
        consistency: delegated
        source: .
        target: /develop

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "shuttle-proxy"
    ports:
      - "9182:9182"
    environment:
      HTTP_TENDERMINT_URL: https://cosmos-rest.publicnode.com
      WS_TENDERMINT_URL: https://cosmos-rest.publicnode.com/websocket
      RPC_TENDERMINT_URL: https://cosmos-rpc.publicnode.com:443
      HTTP_LISTEN_ADDR: 0.0.0.0:9182
      LOG_LEVEL: info
      BECH_PREFIX: cosmos
      COIN_DENOM: uatom
