// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceABCIQueryReader is a Reader for the ServiceABCIQuery structure.
type ServiceABCIQueryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceABCIQueryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceABCIQueryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewServiceABCIQueryDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceABCIQueryOK creates a ServiceABCIQueryOK with default headers values
func NewServiceABCIQueryOK() *ServiceABCIQueryOK {
	return &ServiceABCIQueryOK{}
}

/*
ServiceABCIQueryOK describes a response with status code 200, with default header values.

A successful response.
*/
type ServiceABCIQueryOK struct {
	Payload *ServiceABCIQueryOKBody
}

// IsSuccess returns true when this service a b c i query o k response has a 2xx status code
func (o *ServiceABCIQueryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this service a b c i query o k response has a 3xx status code
func (o *ServiceABCIQueryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this service a b c i query o k response has a 4xx status code
func (o *ServiceABCIQueryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this service a b c i query o k response has a 5xx status code
func (o *ServiceABCIQueryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this service a b c i query o k response a status code equal to that given
func (o *ServiceABCIQueryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the service a b c i query o k response
func (o *ServiceABCIQueryOK) Code() int {
	return 200
}

func (o *ServiceABCIQueryOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/abci_query][%d] serviceABCIQueryOK %s", 200, payload)
}

func (o *ServiceABCIQueryOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/abci_query][%d] serviceABCIQueryOK %s", 200, payload)
}

func (o *ServiceABCIQueryOK) GetPayload() *ServiceABCIQueryOKBody {
	return o.Payload
}

func (o *ServiceABCIQueryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServiceABCIQueryOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceABCIQueryDefault creates a ServiceABCIQueryDefault with default headers values
func NewServiceABCIQueryDefault(code int) *ServiceABCIQueryDefault {
	return &ServiceABCIQueryDefault{
		_statusCode: code,
	}
}

/*
ServiceABCIQueryDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ServiceABCIQueryDefault struct {
	_statusCode int

	Payload *ServiceABCIQueryDefaultBody
}

// IsSuccess returns true when this service a b c i query default response has a 2xx status code
func (o *ServiceABCIQueryDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this service a b c i query default response has a 3xx status code
func (o *ServiceABCIQueryDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this service a b c i query default response has a 4xx status code
func (o *ServiceABCIQueryDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this service a b c i query default response has a 5xx status code
func (o *ServiceABCIQueryDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this service a b c i query default response a status code equal to that given
func (o *ServiceABCIQueryDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the service a b c i query default response
func (o *ServiceABCIQueryDefault) Code() int {
	return o._statusCode
}

func (o *ServiceABCIQueryDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/abci_query][%d] Service_ABCIQuery default %s", o._statusCode, payload)
}

func (o *ServiceABCIQueryDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/abci_query][%d] Service_ABCIQuery default %s", o._statusCode, payload)
}

func (o *ServiceABCIQueryDefault) GetPayload() *ServiceABCIQueryDefaultBody {
	return o.Payload
}

func (o *ServiceABCIQueryDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServiceABCIQueryDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
ServiceABCIQueryDefaultBody service a b c i query default body
swagger:model ServiceABCIQueryDefaultBody
*/
type ServiceABCIQueryDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*ServiceABCIQueryDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this service a b c i query default body
func (o *ServiceABCIQueryDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceABCIQueryDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_ABCIQuery default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_ABCIQuery default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this service a b c i query default body based on the context it is used
func (o *ServiceABCIQueryDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceABCIQueryDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_ABCIQuery default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_ABCIQuery default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceABCIQueryDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceABCIQueryDefaultBody) UnmarshalBinary(b []byte) error {
	var res ServiceABCIQueryDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceABCIQueryDefaultBodyDetailsItems0 service a b c i query default body details items0
swagger:model ServiceABCIQueryDefaultBodyDetailsItems0
*/
type ServiceABCIQueryDefaultBodyDetailsItems0 struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// service a b c i query default body details items0
	ServiceABCIQueryDefaultBodyDetailsItems0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *ServiceABCIQueryDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv ServiceABCIQueryDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.ServiceABCIQueryDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o ServiceABCIQueryDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.ServiceABCIQueryDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.ServiceABCIQueryDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this service a b c i query default body details items0
func (o *ServiceABCIQueryDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service a b c i query default body details items0 based on context it is used
func (o *ServiceABCIQueryDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceABCIQueryDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceABCIQueryDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res ServiceABCIQueryDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceABCIQueryOKBody service a b c i query o k body
swagger:model ServiceABCIQueryOKBody
*/
type ServiceABCIQueryOKBody struct {

	// code
	Code int64 `json:"code,omitempty"`

	// codespace
	Codespace string `json:"codespace,omitempty"`

	// height
	Height string `json:"height,omitempty"`

	// index
	Index string `json:"index,omitempty"`

	// info
	Info string `json:"info,omitempty"`

	// key
	// Format: byte
	Key strfmt.Base64 `json:"key,omitempty"`

	// log
	Log string `json:"log,omitempty"`

	// proof ops
	ProofOps *ServiceABCIQueryOKBodyProofOps `json:"proof_ops,omitempty"`

	// value
	// Format: byte
	Value strfmt.Base64 `json:"value,omitempty"`
}

// Validate validates this service a b c i query o k body
func (o *ServiceABCIQueryOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateProofOps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceABCIQueryOKBody) validateProofOps(formats strfmt.Registry) error {
	if swag.IsZero(o.ProofOps) { // not required
		return nil
	}

	if o.ProofOps != nil {
		if err := o.ProofOps.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("serviceABCIQueryOK" + "." + "proof_ops")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("serviceABCIQueryOK" + "." + "proof_ops")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this service a b c i query o k body based on the context it is used
func (o *ServiceABCIQueryOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateProofOps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceABCIQueryOKBody) contextValidateProofOps(ctx context.Context, formats strfmt.Registry) error {

	if o.ProofOps != nil {

		if swag.IsZero(o.ProofOps) { // not required
			return nil
		}

		if err := o.ProofOps.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("serviceABCIQueryOK" + "." + "proof_ops")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("serviceABCIQueryOK" + "." + "proof_ops")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceABCIQueryOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceABCIQueryOKBody) UnmarshalBinary(b []byte) error {
	var res ServiceABCIQueryOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceABCIQueryOKBodyProofOps service a b c i query o k body proof ops
swagger:model ServiceABCIQueryOKBodyProofOps
*/
type ServiceABCIQueryOKBodyProofOps struct {

	// ops
	Ops []*ServiceABCIQueryOKBodyProofOpsOpsItems0 `json:"ops"`
}

// Validate validates this service a b c i query o k body proof ops
func (o *ServiceABCIQueryOKBodyProofOps) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateOps(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceABCIQueryOKBodyProofOps) validateOps(formats strfmt.Registry) error {
	if swag.IsZero(o.Ops) { // not required
		return nil
	}

	for i := 0; i < len(o.Ops); i++ {
		if swag.IsZero(o.Ops[i]) { // not required
			continue
		}

		if o.Ops[i] != nil {
			if err := o.Ops[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("serviceABCIQueryOK" + "." + "proof_ops" + "." + "ops" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("serviceABCIQueryOK" + "." + "proof_ops" + "." + "ops" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this service a b c i query o k body proof ops based on the context it is used
func (o *ServiceABCIQueryOKBodyProofOps) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateOps(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceABCIQueryOKBodyProofOps) contextValidateOps(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Ops); i++ {

		if o.Ops[i] != nil {

			if swag.IsZero(o.Ops[i]) { // not required
				return nil
			}

			if err := o.Ops[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("serviceABCIQueryOK" + "." + "proof_ops" + "." + "ops" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("serviceABCIQueryOK" + "." + "proof_ops" + "." + "ops" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceABCIQueryOKBodyProofOps) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceABCIQueryOKBodyProofOps) UnmarshalBinary(b []byte) error {
	var res ServiceABCIQueryOKBodyProofOps
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceABCIQueryOKBodyProofOpsOpsItems0 service a b c i query o k body proof ops ops items0
swagger:model ServiceABCIQueryOKBodyProofOpsOpsItems0
*/
type ServiceABCIQueryOKBodyProofOpsOpsItems0 struct {

	// data
	// Format: byte
	Data strfmt.Base64 `json:"data,omitempty"`

	// key
	// Format: byte
	Key strfmt.Base64 `json:"key,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this service a b c i query o k body proof ops ops items0
func (o *ServiceABCIQueryOKBodyProofOpsOpsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service a b c i query o k body proof ops ops items0 based on context it is used
func (o *ServiceABCIQueryOKBodyProofOpsOpsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceABCIQueryOKBodyProofOpsOpsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceABCIQueryOKBodyProofOpsOpsItems0) UnmarshalBinary(b []byte) error {
	var res ServiceABCIQueryOKBodyProofOpsOpsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
