// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceGetSyncingReader is a Reader for the ServiceGetSyncing structure.
type ServiceGetSyncingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceGetSyncingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceGetSyncingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewServiceGetSyncingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceGetSyncingOK creates a ServiceGetSyncingOK with default headers values
func NewServiceGetSyncingOK() *ServiceGetSyncingOK {
	return &ServiceGetSyncingOK{}
}

/*
ServiceGetSyncingOK describes a response with status code 200, with default header values.

A successful response.
*/
type ServiceGetSyncingOK struct {
	Payload *ServiceGetSyncingOKBody
}

// IsSuccess returns true when this service get syncing o k response has a 2xx status code
func (o *ServiceGetSyncingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this service get syncing o k response has a 3xx status code
func (o *ServiceGetSyncingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this service get syncing o k response has a 4xx status code
func (o *ServiceGetSyncingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this service get syncing o k response has a 5xx status code
func (o *ServiceGetSyncingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this service get syncing o k response a status code equal to that given
func (o *ServiceGetSyncingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the service get syncing o k response
func (o *ServiceGetSyncingOK) Code() int {
	return 200
}

func (o *ServiceGetSyncingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/syncing][%d] serviceGetSyncingOK %s", 200, payload)
}

func (o *ServiceGetSyncingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/syncing][%d] serviceGetSyncingOK %s", 200, payload)
}

func (o *ServiceGetSyncingOK) GetPayload() *ServiceGetSyncingOKBody {
	return o.Payload
}

func (o *ServiceGetSyncingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServiceGetSyncingOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceGetSyncingDefault creates a ServiceGetSyncingDefault with default headers values
func NewServiceGetSyncingDefault(code int) *ServiceGetSyncingDefault {
	return &ServiceGetSyncingDefault{
		_statusCode: code,
	}
}

/*
ServiceGetSyncingDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ServiceGetSyncingDefault struct {
	_statusCode int

	Payload *ServiceGetSyncingDefaultBody
}

// IsSuccess returns true when this service get syncing default response has a 2xx status code
func (o *ServiceGetSyncingDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this service get syncing default response has a 3xx status code
func (o *ServiceGetSyncingDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this service get syncing default response has a 4xx status code
func (o *ServiceGetSyncingDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this service get syncing default response has a 5xx status code
func (o *ServiceGetSyncingDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this service get syncing default response a status code equal to that given
func (o *ServiceGetSyncingDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the service get syncing default response
func (o *ServiceGetSyncingDefault) Code() int {
	return o._statusCode
}

func (o *ServiceGetSyncingDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/syncing][%d] Service_GetSyncing default %s", o._statusCode, payload)
}

func (o *ServiceGetSyncingDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/syncing][%d] Service_GetSyncing default %s", o._statusCode, payload)
}

func (o *ServiceGetSyncingDefault) GetPayload() *ServiceGetSyncingDefaultBody {
	return o.Payload
}

func (o *ServiceGetSyncingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServiceGetSyncingDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
ServiceGetSyncingDefaultBody service get syncing default body
swagger:model ServiceGetSyncingDefaultBody
*/
type ServiceGetSyncingDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*ServiceGetSyncingDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this service get syncing default body
func (o *ServiceGetSyncingDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetSyncingDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_GetSyncing default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_GetSyncing default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this service get syncing default body based on the context it is used
func (o *ServiceGetSyncingDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetSyncingDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_GetSyncing default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_GetSyncing default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetSyncingDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetSyncingDefaultBody) UnmarshalBinary(b []byte) error {
	var res ServiceGetSyncingDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceGetSyncingDefaultBodyDetailsItems0 service get syncing default body details items0
swagger:model ServiceGetSyncingDefaultBodyDetailsItems0
*/
type ServiceGetSyncingDefaultBodyDetailsItems0 struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// service get syncing default body details items0
	ServiceGetSyncingDefaultBodyDetailsItems0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *ServiceGetSyncingDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv ServiceGetSyncingDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.ServiceGetSyncingDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o ServiceGetSyncingDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.ServiceGetSyncingDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.ServiceGetSyncingDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this service get syncing default body details items0
func (o *ServiceGetSyncingDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service get syncing default body details items0 based on context it is used
func (o *ServiceGetSyncingDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetSyncingDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetSyncingDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res ServiceGetSyncingDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceGetSyncingOKBody service get syncing o k body
swagger:model ServiceGetSyncingOKBody
*/
type ServiceGetSyncingOKBody struct {

	// syncing
	Syncing bool `json:"syncing,omitempty"`
}

// Validate validates this service get syncing o k body
func (o *ServiceGetSyncingOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service get syncing o k body based on context it is used
func (o *ServiceGetSyncingOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetSyncingOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetSyncingOKBody) UnmarshalBinary(b []byte) error {
	var res ServiceGetSyncingOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
