// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceGetLatestValidatorSetReader is a Reader for the ServiceGetLatestValidatorSet structure.
type ServiceGetLatestValidatorSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceGetLatestValidatorSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceGetLatestValidatorSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewServiceGetLatestValidatorSetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceGetLatestValidatorSetOK creates a ServiceGetLatestValidatorSetOK with default headers values
func NewServiceGetLatestValidatorSetOK() *ServiceGetLatestValidatorSetOK {
	return &ServiceGetLatestValidatorSetOK{}
}

/*
ServiceGetLatestValidatorSetOK describes a response with status code 200, with default header values.

A successful response.
*/
type ServiceGetLatestValidatorSetOK struct {
	Payload *ServiceGetLatestValidatorSetOKBody
}

// IsSuccess returns true when this service get latest validator set o k response has a 2xx status code
func (o *ServiceGetLatestValidatorSetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this service get latest validator set o k response has a 3xx status code
func (o *ServiceGetLatestValidatorSetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this service get latest validator set o k response has a 4xx status code
func (o *ServiceGetLatestValidatorSetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this service get latest validator set o k response has a 5xx status code
func (o *ServiceGetLatestValidatorSetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this service get latest validator set o k response a status code equal to that given
func (o *ServiceGetLatestValidatorSetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the service get latest validator set o k response
func (o *ServiceGetLatestValidatorSetOK) Code() int {
	return 200
}

func (o *ServiceGetLatestValidatorSetOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/validatorsets/latest][%d] serviceGetLatestValidatorSetOK %s", 200, payload)
}

func (o *ServiceGetLatestValidatorSetOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/validatorsets/latest][%d] serviceGetLatestValidatorSetOK %s", 200, payload)
}

func (o *ServiceGetLatestValidatorSetOK) GetPayload() *ServiceGetLatestValidatorSetOKBody {
	return o.Payload
}

func (o *ServiceGetLatestValidatorSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServiceGetLatestValidatorSetOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceGetLatestValidatorSetDefault creates a ServiceGetLatestValidatorSetDefault with default headers values
func NewServiceGetLatestValidatorSetDefault(code int) *ServiceGetLatestValidatorSetDefault {
	return &ServiceGetLatestValidatorSetDefault{
		_statusCode: code,
	}
}

/*
ServiceGetLatestValidatorSetDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ServiceGetLatestValidatorSetDefault struct {
	_statusCode int

	Payload *ServiceGetLatestValidatorSetDefaultBody
}

// IsSuccess returns true when this service get latest validator set default response has a 2xx status code
func (o *ServiceGetLatestValidatorSetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this service get latest validator set default response has a 3xx status code
func (o *ServiceGetLatestValidatorSetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this service get latest validator set default response has a 4xx status code
func (o *ServiceGetLatestValidatorSetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this service get latest validator set default response has a 5xx status code
func (o *ServiceGetLatestValidatorSetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this service get latest validator set default response a status code equal to that given
func (o *ServiceGetLatestValidatorSetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the service get latest validator set default response
func (o *ServiceGetLatestValidatorSetDefault) Code() int {
	return o._statusCode
}

func (o *ServiceGetLatestValidatorSetDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/validatorsets/latest][%d] Service_GetLatestValidatorSet default %s", o._statusCode, payload)
}

func (o *ServiceGetLatestValidatorSetDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/base/tendermint/v1beta1/validatorsets/latest][%d] Service_GetLatestValidatorSet default %s", o._statusCode, payload)
}

func (o *ServiceGetLatestValidatorSetDefault) GetPayload() *ServiceGetLatestValidatorSetDefaultBody {
	return o.Payload
}

func (o *ServiceGetLatestValidatorSetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServiceGetLatestValidatorSetDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
ServiceGetLatestValidatorSetDefaultBody service get latest validator set default body
swagger:model ServiceGetLatestValidatorSetDefaultBody
*/
type ServiceGetLatestValidatorSetDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*ServiceGetLatestValidatorSetDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this service get latest validator set default body
func (o *ServiceGetLatestValidatorSetDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetLatestValidatorSetDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_GetLatestValidatorSet default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_GetLatestValidatorSet default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this service get latest validator set default body based on the context it is used
func (o *ServiceGetLatestValidatorSetDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetLatestValidatorSetDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_GetLatestValidatorSet default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_GetLatestValidatorSet default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetDefaultBody) UnmarshalBinary(b []byte) error {
	var res ServiceGetLatestValidatorSetDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceGetLatestValidatorSetDefaultBodyDetailsItems0 service get latest validator set default body details items0
swagger:model ServiceGetLatestValidatorSetDefaultBodyDetailsItems0
*/
type ServiceGetLatestValidatorSetDefaultBodyDetailsItems0 struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// service get latest validator set default body details items0
	ServiceGetLatestValidatorSetDefaultBodyDetailsItems0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *ServiceGetLatestValidatorSetDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv ServiceGetLatestValidatorSetDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.ServiceGetLatestValidatorSetDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o ServiceGetLatestValidatorSetDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.ServiceGetLatestValidatorSetDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.ServiceGetLatestValidatorSetDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this service get latest validator set default body details items0
func (o *ServiceGetLatestValidatorSetDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service get latest validator set default body details items0 based on context it is used
func (o *ServiceGetLatestValidatorSetDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res ServiceGetLatestValidatorSetDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceGetLatestValidatorSetOKBody service get latest validator set o k body
swagger:model ServiceGetLatestValidatorSetOKBody
*/
type ServiceGetLatestValidatorSetOKBody struct {

	// block height
	BlockHeight string `json:"block_height,omitempty"`

	// pagination
	Pagination *ServiceGetLatestValidatorSetOKBodyPagination `json:"pagination,omitempty"`

	// validators
	Validators []*ServiceGetLatestValidatorSetOKBodyValidatorsItems0 `json:"validators"`
}

// Validate validates this service get latest validator set o k body
func (o *ServiceGetLatestValidatorSetOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateValidators(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetLatestValidatorSetOKBody) validatePagination(formats strfmt.Registry) error {
	if swag.IsZero(o.Pagination) { // not required
		return nil
	}

	if o.Pagination != nil {
		if err := o.Pagination.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("serviceGetLatestValidatorSetOK" + "." + "pagination")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("serviceGetLatestValidatorSetOK" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

func (o *ServiceGetLatestValidatorSetOKBody) validateValidators(formats strfmt.Registry) error {
	if swag.IsZero(o.Validators) { // not required
		return nil
	}

	for i := 0; i < len(o.Validators); i++ {
		if swag.IsZero(o.Validators[i]) { // not required
			continue
		}

		if o.Validators[i] != nil {
			if err := o.Validators[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("serviceGetLatestValidatorSetOK" + "." + "validators" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("serviceGetLatestValidatorSetOK" + "." + "validators" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this service get latest validator set o k body based on the context it is used
func (o *ServiceGetLatestValidatorSetOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidatePagination(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateValidators(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetLatestValidatorSetOKBody) contextValidatePagination(ctx context.Context, formats strfmt.Registry) error {

	if o.Pagination != nil {

		if swag.IsZero(o.Pagination) { // not required
			return nil
		}

		if err := o.Pagination.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("serviceGetLatestValidatorSetOK" + "." + "pagination")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("serviceGetLatestValidatorSetOK" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

func (o *ServiceGetLatestValidatorSetOKBody) contextValidateValidators(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Validators); i++ {

		if o.Validators[i] != nil {

			if swag.IsZero(o.Validators[i]) { // not required
				return nil
			}

			if err := o.Validators[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("serviceGetLatestValidatorSetOK" + "." + "validators" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("serviceGetLatestValidatorSetOK" + "." + "validators" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetOKBody) UnmarshalBinary(b []byte) error {
	var res ServiceGetLatestValidatorSetOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceGetLatestValidatorSetOKBodyPagination service get latest validator set o k body pagination
swagger:model ServiceGetLatestValidatorSetOKBodyPagination
*/
type ServiceGetLatestValidatorSetOKBodyPagination struct {

	// next key
	// Format: byte
	NextKey strfmt.Base64 `json:"next_key,omitempty"`

	// total
	Total string `json:"total,omitempty"`
}

// Validate validates this service get latest validator set o k body pagination
func (o *ServiceGetLatestValidatorSetOKBodyPagination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service get latest validator set o k body pagination based on context it is used
func (o *ServiceGetLatestValidatorSetOKBodyPagination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetOKBodyPagination) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetOKBodyPagination) UnmarshalBinary(b []byte) error {
	var res ServiceGetLatestValidatorSetOKBodyPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceGetLatestValidatorSetOKBodyValidatorsItems0 service get latest validator set o k body validators items0
swagger:model ServiceGetLatestValidatorSetOKBodyValidatorsItems0
*/
type ServiceGetLatestValidatorSetOKBodyValidatorsItems0 struct {

	// address
	Address string `json:"address,omitempty"`

	// proposer priority
	ProposerPriority string `json:"proposer_priority,omitempty"`

	// pub key
	PubKey *ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey `json:"pub_key,omitempty"`

	// voting power
	VotingPower string `json:"voting_power,omitempty"`
}

// Validate validates this service get latest validator set o k body validators items0
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePubKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0) validatePubKey(formats strfmt.Registry) error {
	if swag.IsZero(o.PubKey) { // not required
		return nil
	}

	if o.PubKey != nil {
		if err := o.PubKey.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pub_key")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pub_key")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this service get latest validator set o k body validators items0 based on the context it is used
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidatePubKey(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0) contextValidatePubKey(ctx context.Context, formats strfmt.Registry) error {

	if o.PubKey != nil {

		if swag.IsZero(o.PubKey) { // not required
			return nil
		}

		if err := o.PubKey.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("pub_key")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("pub_key")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0) UnmarshalBinary(b []byte) error {
	var res ServiceGetLatestValidatorSetOKBodyValidatorsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey service get latest validator set o k body validators items0 pub key
swagger:model ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey
*/
type ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// service get latest validator set o k body validators items0 pub key
	ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this service get latest validator set o k body validators items0 pub key
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service get latest validator set o k body validators items0 pub key based on context it is used
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey) UnmarshalBinary(b []byte) error {
	var res ServiceGetLatestValidatorSetOKBodyValidatorsItems0PubKey
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
