// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// OrderBy order by
//
// swagger:model OrderBy
type OrderBy string

func NewOrderBy(value OrderBy) *OrderBy {
	return &value
}

// Pointer returns a pointer to a freshly-allocated OrderBy.
func (m OrderBy) Pointer() *OrderBy {
	return &m
}

const (

	// OrderByORDERBYUNSPECIFIED captures enum value "ORDER_BY_UNSPECIFIED"
	OrderByORDERBYUNSPECIFIED OrderBy = "ORDER_BY_UNSPECIFIED"

	// OrderByORDERBYASC captures enum value "ORDER_BY_ASC"
	OrderByORDERBYASC OrderBy = "ORDER_BY_ASC"

	// OrderByORDERBYDESC captures enum value "ORDER_BY_DESC"
	OrderByORDERBYDESC OrderBy = "ORDER_BY_DESC"
)

// for schema
var orderByEnum []interface{}

func init() {
	var res []OrderBy
	if err := json.Unmarshal([]byte(`["ORDER_BY_UNSPECIFIED","ORDER_BY_ASC","ORDER_BY_DESC"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		orderByEnum = append(orderByEnum, v)
	}
}

func (m OrderBy) validateOrderByEnum(path, location string, value OrderBy) error {
	if err := validate.EnumCase(path, location, value, orderByEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this order by
func (m OrderBy) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateOrderByEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this order by based on context it is used
func (m OrderBy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
