// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TxEncodeAminoResponse tx encode amino response
//
// swagger:model TxEncodeAminoResponse
type TxEncodeAminoResponse struct {

	// amino binary
	// Format: byte
	AminoBinary strfmt.Base64 `json:"amino_binary,omitempty"`
}

// Validate validates this tx encode amino response
func (m *TxEncodeAminoResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tx encode amino response based on context it is used
func (m *TxEncodeAminoResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TxEncodeAminoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TxEncodeAminoResponse) UnmarshalBinary(b []byte) error {
	var res TxEncodeAminoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
