// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fairmath/shuttle/internal/client/tendermint/api/internal/txs/models"
)

// ServiceGetBlockWithTxsReader is a Reader for the ServiceGetBlockWithTxs structure.
type ServiceGetBlockWithTxsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceGetBlockWithTxsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceGetBlockWithTxsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewServiceGetBlockWithTxsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceGetBlockWithTxsOK creates a ServiceGetBlockWithTxsOK with default headers values
func NewServiceGetBlockWithTxsOK() *ServiceGetBlockWithTxsOK {
	return &ServiceGetBlockWithTxsOK{}
}

/*
ServiceGetBlockWithTxsOK describes a response with status code 200, with default header values.

A successful response.
*/
type ServiceGetBlockWithTxsOK struct {
	Payload *models.BlockWithTxs
}

// IsSuccess returns true when this service get block with txs o k response has a 2xx status code
func (o *ServiceGetBlockWithTxsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this service get block with txs o k response has a 3xx status code
func (o *ServiceGetBlockWithTxsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this service get block with txs o k response has a 4xx status code
func (o *ServiceGetBlockWithTxsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this service get block with txs o k response has a 5xx status code
func (o *ServiceGetBlockWithTxsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this service get block with txs o k response a status code equal to that given
func (o *ServiceGetBlockWithTxsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the service get block with txs o k response
func (o *ServiceGetBlockWithTxsOK) Code() int {
	return 200
}

func (o *ServiceGetBlockWithTxsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/tx/v1beta1/txs/block/{height}][%d] serviceGetBlockWithTxsOK %s", 200, payload)
}

func (o *ServiceGetBlockWithTxsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/tx/v1beta1/txs/block/{height}][%d] serviceGetBlockWithTxsOK %s", 200, payload)
}

func (o *ServiceGetBlockWithTxsOK) GetPayload() *models.BlockWithTxs {
	return o.Payload
}

func (o *ServiceGetBlockWithTxsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BlockWithTxs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceGetBlockWithTxsDefault creates a ServiceGetBlockWithTxsDefault with default headers values
func NewServiceGetBlockWithTxsDefault(code int) *ServiceGetBlockWithTxsDefault {
	return &ServiceGetBlockWithTxsDefault{
		_statusCode: code,
	}
}

/*
ServiceGetBlockWithTxsDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ServiceGetBlockWithTxsDefault struct {
	_statusCode int

	Payload *ServiceGetBlockWithTxsDefaultBody
}

// IsSuccess returns true when this service get block with txs default response has a 2xx status code
func (o *ServiceGetBlockWithTxsDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this service get block with txs default response has a 3xx status code
func (o *ServiceGetBlockWithTxsDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this service get block with txs default response has a 4xx status code
func (o *ServiceGetBlockWithTxsDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this service get block with txs default response has a 5xx status code
func (o *ServiceGetBlockWithTxsDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this service get block with txs default response a status code equal to that given
func (o *ServiceGetBlockWithTxsDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the service get block with txs default response
func (o *ServiceGetBlockWithTxsDefault) Code() int {
	return o._statusCode
}

func (o *ServiceGetBlockWithTxsDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/tx/v1beta1/txs/block/{height}][%d] Service_GetBlockWithTxs default %s", o._statusCode, payload)
}

func (o *ServiceGetBlockWithTxsDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/tx/v1beta1/txs/block/{height}][%d] Service_GetBlockWithTxs default %s", o._statusCode, payload)
}

func (o *ServiceGetBlockWithTxsDefault) GetPayload() *ServiceGetBlockWithTxsDefaultBody {
	return o.Payload
}

func (o *ServiceGetBlockWithTxsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServiceGetBlockWithTxsDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
ServiceGetBlockWithTxsDefaultBody service get block with txs default body
swagger:model ServiceGetBlockWithTxsDefaultBody
*/
type ServiceGetBlockWithTxsDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*ServiceGetBlockWithTxsDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this service get block with txs default body
func (o *ServiceGetBlockWithTxsDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetBlockWithTxsDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_GetBlockWithTxs default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_GetBlockWithTxs default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this service get block with txs default body based on the context it is used
func (o *ServiceGetBlockWithTxsDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceGetBlockWithTxsDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_GetBlockWithTxs default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_GetBlockWithTxs default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetBlockWithTxsDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetBlockWithTxsDefaultBody) UnmarshalBinary(b []byte) error {
	var res ServiceGetBlockWithTxsDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceGetBlockWithTxsDefaultBodyDetailsItems0 service get block with txs default body details items0
swagger:model ServiceGetBlockWithTxsDefaultBodyDetailsItems0
*/
type ServiceGetBlockWithTxsDefaultBodyDetailsItems0 struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// service get block with txs default body details items0
	ServiceGetBlockWithTxsDefaultBodyDetailsItems0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *ServiceGetBlockWithTxsDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv ServiceGetBlockWithTxsDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.ServiceGetBlockWithTxsDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o ServiceGetBlockWithTxsDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.ServiceGetBlockWithTxsDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.ServiceGetBlockWithTxsDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this service get block with txs default body details items0
func (o *ServiceGetBlockWithTxsDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service get block with txs default body details items0 based on context it is used
func (o *ServiceGetBlockWithTxsDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceGetBlockWithTxsDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceGetBlockWithTxsDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res ServiceGetBlockWithTxsDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
