// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fairmath/shuttle/internal/client/tendermint/api/internal/txs/models"
)

// ServiceTxDecodeReader is a Reader for the ServiceTxDecode structure.
type ServiceTxDecodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceTxDecodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceTxDecodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewServiceTxDecodeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceTxDecodeOK creates a ServiceTxDecodeOK with default headers values
func NewServiceTxDecodeOK() *ServiceTxDecodeOK {
	return &ServiceTxDecodeOK{}
}

/*
ServiceTxDecodeOK describes a response with status code 200, with default header values.

A successful response.
*/
type ServiceTxDecodeOK struct {
	Payload *models.TxDecodeResponse
}

// IsSuccess returns true when this service tx decode o k response has a 2xx status code
func (o *ServiceTxDecodeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this service tx decode o k response has a 3xx status code
func (o *ServiceTxDecodeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this service tx decode o k response has a 4xx status code
func (o *ServiceTxDecodeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this service tx decode o k response has a 5xx status code
func (o *ServiceTxDecodeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this service tx decode o k response a status code equal to that given
func (o *ServiceTxDecodeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the service tx decode o k response
func (o *ServiceTxDecodeOK) Code() int {
	return 200
}

func (o *ServiceTxDecodeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cosmos/tx/v1beta1/decode][%d] serviceTxDecodeOK %s", 200, payload)
}

func (o *ServiceTxDecodeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cosmos/tx/v1beta1/decode][%d] serviceTxDecodeOK %s", 200, payload)
}

func (o *ServiceTxDecodeOK) GetPayload() *models.TxDecodeResponse {
	return o.Payload
}

func (o *ServiceTxDecodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TxDecodeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceTxDecodeDefault creates a ServiceTxDecodeDefault with default headers values
func NewServiceTxDecodeDefault(code int) *ServiceTxDecodeDefault {
	return &ServiceTxDecodeDefault{
		_statusCode: code,
	}
}

/*
ServiceTxDecodeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ServiceTxDecodeDefault struct {
	_statusCode int

	Payload *ServiceTxDecodeDefaultBody
}

// IsSuccess returns true when this service tx decode default response has a 2xx status code
func (o *ServiceTxDecodeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this service tx decode default response has a 3xx status code
func (o *ServiceTxDecodeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this service tx decode default response has a 4xx status code
func (o *ServiceTxDecodeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this service tx decode default response has a 5xx status code
func (o *ServiceTxDecodeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this service tx decode default response a status code equal to that given
func (o *ServiceTxDecodeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the service tx decode default response
func (o *ServiceTxDecodeDefault) Code() int {
	return o._statusCode
}

func (o *ServiceTxDecodeDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cosmos/tx/v1beta1/decode][%d] Service_TxDecode default %s", o._statusCode, payload)
}

func (o *ServiceTxDecodeDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /cosmos/tx/v1beta1/decode][%d] Service_TxDecode default %s", o._statusCode, payload)
}

func (o *ServiceTxDecodeDefault) GetPayload() *ServiceTxDecodeDefaultBody {
	return o.Payload
}

func (o *ServiceTxDecodeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ServiceTxDecodeDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
ServiceTxDecodeBody service tx decode body
swagger:model ServiceTxDecodeBody
*/
type ServiceTxDecodeBody struct {

	// tx bytes
	// Format: byte
	TxBytes strfmt.Base64 `json:"tx_bytes,omitempty"`
}

// Validate validates this service tx decode body
func (o *ServiceTxDecodeBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service tx decode body based on context it is used
func (o *ServiceTxDecodeBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceTxDecodeBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceTxDecodeBody) UnmarshalBinary(b []byte) error {
	var res ServiceTxDecodeBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceTxDecodeDefaultBody service tx decode default body
swagger:model ServiceTxDecodeDefaultBody
*/
type ServiceTxDecodeDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*ServiceTxDecodeDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this service tx decode default body
func (o *ServiceTxDecodeDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceTxDecodeDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_TxDecode default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_TxDecode default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this service tx decode default body based on the context it is used
func (o *ServiceTxDecodeDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ServiceTxDecodeDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Service_TxDecode default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Service_TxDecode default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ServiceTxDecodeDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceTxDecodeDefaultBody) UnmarshalBinary(b []byte) error {
	var res ServiceTxDecodeDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
ServiceTxDecodeDefaultBodyDetailsItems0 service tx decode default body details items0
swagger:model ServiceTxDecodeDefaultBodyDetailsItems0
*/
type ServiceTxDecodeDefaultBodyDetailsItems0 struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// service tx decode default body details items0
	ServiceTxDecodeDefaultBodyDetailsItems0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *ServiceTxDecodeDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv ServiceTxDecodeDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.ServiceTxDecodeDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o ServiceTxDecodeDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.ServiceTxDecodeDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.ServiceTxDecodeDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this service tx decode default body details items0
func (o *ServiceTxDecodeDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service tx decode default body details items0 based on context it is used
func (o *ServiceTxDecodeDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ServiceTxDecodeDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ServiceTxDecodeDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res ServiceTxDecodeDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
