// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewServiceTxDecodeParams creates a new ServiceTxDecodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewServiceTxDecodeParams() *ServiceTxDecodeParams {
	return &ServiceTxDecodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewServiceTxDecodeParamsWithTimeout creates a new ServiceTxDecodeParams object
// with the ability to set a timeout on a request.
func NewServiceTxDecodeParamsWithTimeout(timeout time.Duration) *ServiceTxDecodeParams {
	return &ServiceTxDecodeParams{
		timeout: timeout,
	}
}

// NewServiceTxDecodeParamsWithContext creates a new ServiceTxDecodeParams object
// with the ability to set a context for a request.
func NewServiceTxDecodeParamsWithContext(ctx context.Context) *ServiceTxDecodeParams {
	return &ServiceTxDecodeParams{
		Context: ctx,
	}
}

// NewServiceTxDecodeParamsWithHTTPClient creates a new ServiceTxDecodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewServiceTxDecodeParamsWithHTTPClient(client *http.Client) *ServiceTxDecodeParams {
	return &ServiceTxDecodeParams{
		HTTPClient: client,
	}
}

/*
ServiceTxDecodeParams contains all the parameters to send to the API endpoint

	for the service tx decode operation.

	Typically these are written to a http.Request.
*/
type ServiceTxDecodeParams struct {

	// Body.
	Body ServiceTxDecodeBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the service tx decode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServiceTxDecodeParams) WithDefaults() *ServiceTxDecodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the service tx decode params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ServiceTxDecodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the service tx decode params
func (o *ServiceTxDecodeParams) WithTimeout(timeout time.Duration) *ServiceTxDecodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service tx decode params
func (o *ServiceTxDecodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service tx decode params
func (o *ServiceTxDecodeParams) WithContext(ctx context.Context) *ServiceTxDecodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service tx decode params
func (o *ServiceTxDecodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the service tx decode params
func (o *ServiceTxDecodeParams) WithHTTPClient(client *http.Client) *ServiceTxDecodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the service tx decode params
func (o *ServiceTxDecodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the service tx decode params
func (o *ServiceTxDecodeParams) WithBody(body ServiceTxDecodeBody) *ServiceTxDecodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the service tx decode params
func (o *ServiceTxDecodeParams) SetBody(body ServiceTxDecodeBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceTxDecodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
