// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQuerySupplyOfParams creates a new QuerySupplyOfParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQuerySupplyOfParams() *QuerySupplyOfParams {
	return &QuerySupplyOfParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQuerySupplyOfParamsWithTimeout creates a new QuerySupplyOfParams object
// with the ability to set a timeout on a request.
func NewQuerySupplyOfParamsWithTimeout(timeout time.Duration) *QuerySupplyOfParams {
	return &QuerySupplyOfParams{
		timeout: timeout,
	}
}

// NewQuerySupplyOfParamsWithContext creates a new QuerySupplyOfParams object
// with the ability to set a context for a request.
func NewQuerySupplyOfParamsWithContext(ctx context.Context) *QuerySupplyOfParams {
	return &QuerySupplyOfParams{
		Context: ctx,
	}
}

// NewQuerySupplyOfParamsWithHTTPClient creates a new QuerySupplyOfParams object
// with the ability to set a custom HTTPClient for a request.
func NewQuerySupplyOfParamsWithHTTPClient(client *http.Client) *QuerySupplyOfParams {
	return &QuerySupplyOfParams{
		HTTPClient: client,
	}
}

/*
QuerySupplyOfParams contains all the parameters to send to the API endpoint

	for the query supply of operation.

	Typically these are written to a http.Request.
*/
type QuerySupplyOfParams struct {

	// Denom.
	Denom *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query supply of params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuerySupplyOfParams) WithDefaults() *QuerySupplyOfParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query supply of params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QuerySupplyOfParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query supply of params
func (o *QuerySupplyOfParams) WithTimeout(timeout time.Duration) *QuerySupplyOfParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query supply of params
func (o *QuerySupplyOfParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query supply of params
func (o *QuerySupplyOfParams) WithContext(ctx context.Context) *QuerySupplyOfParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query supply of params
func (o *QuerySupplyOfParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query supply of params
func (o *QuerySupplyOfParams) WithHTTPClient(client *http.Client) *QuerySupplyOfParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query supply of params
func (o *QuerySupplyOfParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDenom adds the denom to the query supply of params
func (o *QuerySupplyOfParams) WithDenom(denom *string) *QuerySupplyOfParams {
	o.SetDenom(denom)
	return o
}

// SetDenom adds the denom to the query supply of params
func (o *QuerySupplyOfParams) SetDenom(denom *string) {
	o.Denom = denom
}

// WriteToRequest writes these params to a swagger request
func (o *QuerySupplyOfParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Denom != nil {

		// query param denom
		var qrDenom string

		if o.Denom != nil {
			qrDenom = *o.Denom
		}
		qDenom := qrDenom
		if qDenom != "" {

			if err := r.SetQueryParam("denom", qDenom); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
