// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QueryDenomMetadataByQueryStringReader is a Reader for the QueryDenomMetadataByQueryString structure.
type QueryDenomMetadataByQueryStringReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryDenomMetadataByQueryStringReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryDenomMetadataByQueryStringOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewQueryDenomMetadataByQueryStringDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewQueryDenomMetadataByQueryStringOK creates a QueryDenomMetadataByQueryStringOK with default headers values
func NewQueryDenomMetadataByQueryStringOK() *QueryDenomMetadataByQueryStringOK {
	return &QueryDenomMetadataByQueryStringOK{}
}

/*
QueryDenomMetadataByQueryStringOK describes a response with status code 200, with default header values.

A successful response.
*/
type QueryDenomMetadataByQueryStringOK struct {
	Payload *QueryDenomMetadataByQueryStringOKBody
}

// IsSuccess returns true when this query denom metadata by query string o k response has a 2xx status code
func (o *QueryDenomMetadataByQueryStringOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this query denom metadata by query string o k response has a 3xx status code
func (o *QueryDenomMetadataByQueryStringOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query denom metadata by query string o k response has a 4xx status code
func (o *QueryDenomMetadataByQueryStringOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this query denom metadata by query string o k response has a 5xx status code
func (o *QueryDenomMetadataByQueryStringOK) IsServerError() bool {
	return false
}

// IsCode returns true when this query denom metadata by query string o k response a status code equal to that given
func (o *QueryDenomMetadataByQueryStringOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the query denom metadata by query string o k response
func (o *QueryDenomMetadataByQueryStringOK) Code() int {
	return 200
}

func (o *QueryDenomMetadataByQueryStringOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/bank/v1beta1/denoms_metadata_by_query_string][%d] queryDenomMetadataByQueryStringOK %s", 200, payload)
}

func (o *QueryDenomMetadataByQueryStringOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/bank/v1beta1/denoms_metadata_by_query_string][%d] queryDenomMetadataByQueryStringOK %s", 200, payload)
}

func (o *QueryDenomMetadataByQueryStringOK) GetPayload() *QueryDenomMetadataByQueryStringOKBody {
	return o.Payload
}

func (o *QueryDenomMetadataByQueryStringOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(QueryDenomMetadataByQueryStringOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryDenomMetadataByQueryStringDefault creates a QueryDenomMetadataByQueryStringDefault with default headers values
func NewQueryDenomMetadataByQueryStringDefault(code int) *QueryDenomMetadataByQueryStringDefault {
	return &QueryDenomMetadataByQueryStringDefault{
		_statusCode: code,
	}
}

/*
QueryDenomMetadataByQueryStringDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type QueryDenomMetadataByQueryStringDefault struct {
	_statusCode int

	Payload *QueryDenomMetadataByQueryStringDefaultBody
}

// IsSuccess returns true when this query denom metadata by query string default response has a 2xx status code
func (o *QueryDenomMetadataByQueryStringDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this query denom metadata by query string default response has a 3xx status code
func (o *QueryDenomMetadataByQueryStringDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this query denom metadata by query string default response has a 4xx status code
func (o *QueryDenomMetadataByQueryStringDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this query denom metadata by query string default response has a 5xx status code
func (o *QueryDenomMetadataByQueryStringDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this query denom metadata by query string default response a status code equal to that given
func (o *QueryDenomMetadataByQueryStringDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the query denom metadata by query string default response
func (o *QueryDenomMetadataByQueryStringDefault) Code() int {
	return o._statusCode
}

func (o *QueryDenomMetadataByQueryStringDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/bank/v1beta1/denoms_metadata_by_query_string][%d] Query_DenomMetadataByQueryString default %s", o._statusCode, payload)
}

func (o *QueryDenomMetadataByQueryStringDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/bank/v1beta1/denoms_metadata_by_query_string][%d] Query_DenomMetadataByQueryString default %s", o._statusCode, payload)
}

func (o *QueryDenomMetadataByQueryStringDefault) GetPayload() *QueryDenomMetadataByQueryStringDefaultBody {
	return o.Payload
}

func (o *QueryDenomMetadataByQueryStringDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(QueryDenomMetadataByQueryStringDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
QueryDenomMetadataByQueryStringDefaultBody query denom metadata by query string default body
swagger:model QueryDenomMetadataByQueryStringDefaultBody
*/
type QueryDenomMetadataByQueryStringDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this query denom metadata by query string default body
func (o *QueryDenomMetadataByQueryStringDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryDenomMetadataByQueryStringDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Query_DenomMetadataByQueryString default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Query_DenomMetadataByQueryString default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this query denom metadata by query string default body based on the context it is used
func (o *QueryDenomMetadataByQueryStringDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryDenomMetadataByQueryStringDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Query_DenomMetadataByQueryString default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Query_DenomMetadataByQueryString default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringDefaultBody) UnmarshalBinary(b []byte) error {
	var res QueryDenomMetadataByQueryStringDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0 query denom metadata by query string default body details items0
swagger:model QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0
*/
type QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0 struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// query denom metadata by query string default body details items0
	QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this query denom metadata by query string default body details items0
func (o *QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query denom metadata by query string default body details items0 based on context it is used
func (o *QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res QueryDenomMetadataByQueryStringDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
QueryDenomMetadataByQueryStringOKBody query denom metadata by query string o k body
swagger:model QueryDenomMetadataByQueryStringOKBody
*/
type QueryDenomMetadataByQueryStringOKBody struct {

	// metadata
	Metadata *QueryDenomMetadataByQueryStringOKBodyMetadata `json:"metadata,omitempty"`
}

// Validate validates this query denom metadata by query string o k body
func (o *QueryDenomMetadataByQueryStringOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMetadata(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryDenomMetadataByQueryStringOKBody) validateMetadata(formats strfmt.Registry) error {
	if swag.IsZero(o.Metadata) { // not required
		return nil
	}

	if o.Metadata != nil {
		if err := o.Metadata.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("queryDenomMetadataByQueryStringOK" + "." + "metadata")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("queryDenomMetadataByQueryStringOK" + "." + "metadata")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this query denom metadata by query string o k body based on the context it is used
func (o *QueryDenomMetadataByQueryStringOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateMetadata(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryDenomMetadataByQueryStringOKBody) contextValidateMetadata(ctx context.Context, formats strfmt.Registry) error {

	if o.Metadata != nil {

		if swag.IsZero(o.Metadata) { // not required
			return nil
		}

		if err := o.Metadata.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("queryDenomMetadataByQueryStringOK" + "." + "metadata")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("queryDenomMetadataByQueryStringOK" + "." + "metadata")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringOKBody) UnmarshalBinary(b []byte) error {
	var res QueryDenomMetadataByQueryStringOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
QueryDenomMetadataByQueryStringOKBodyMetadata query denom metadata by query string o k body metadata
swagger:model QueryDenomMetadataByQueryStringOKBodyMetadata
*/
type QueryDenomMetadataByQueryStringOKBodyMetadata struct {

	// base
	Base string `json:"base,omitempty"`

	// denom units
	DenomUnits []*QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0 `json:"denom_units"`

	// description
	Description string `json:"description,omitempty"`

	// display
	Display string `json:"display,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// symbol
	Symbol string `json:"symbol,omitempty"`

	// uri
	URI string `json:"uri,omitempty"`

	// uri hash
	URIHash string `json:"uri_hash,omitempty"`
}

// Validate validates this query denom metadata by query string o k body metadata
func (o *QueryDenomMetadataByQueryStringOKBodyMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDenomUnits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryDenomMetadataByQueryStringOKBodyMetadata) validateDenomUnits(formats strfmt.Registry) error {
	if swag.IsZero(o.DenomUnits) { // not required
		return nil
	}

	for i := 0; i < len(o.DenomUnits); i++ {
		if swag.IsZero(o.DenomUnits[i]) { // not required
			continue
		}

		if o.DenomUnits[i] != nil {
			if err := o.DenomUnits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("queryDenomMetadataByQueryStringOK" + "." + "metadata" + "." + "denom_units" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("queryDenomMetadataByQueryStringOK" + "." + "metadata" + "." + "denom_units" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this query denom metadata by query string o k body metadata based on the context it is used
func (o *QueryDenomMetadataByQueryStringOKBodyMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDenomUnits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryDenomMetadataByQueryStringOKBodyMetadata) contextValidateDenomUnits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.DenomUnits); i++ {

		if o.DenomUnits[i] != nil {

			if swag.IsZero(o.DenomUnits[i]) { // not required
				return nil
			}

			if err := o.DenomUnits[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("queryDenomMetadataByQueryStringOK" + "." + "metadata" + "." + "denom_units" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("queryDenomMetadataByQueryStringOK" + "." + "metadata" + "." + "denom_units" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringOKBodyMetadata) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringOKBodyMetadata) UnmarshalBinary(b []byte) error {
	var res QueryDenomMetadataByQueryStringOKBodyMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0 query denom metadata by query string o k body metadata denom units items0
swagger:model QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0
*/
type QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0 struct {

	// aliases
	Aliases []string `json:"aliases"`

	// denom
	Denom string `json:"denom,omitempty"`

	// exponent
	Exponent int64 `json:"exponent,omitempty"`
}

// Validate validates this query denom metadata by query string o k body metadata denom units items0
func (o *QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query denom metadata by query string o k body metadata denom units items0 based on context it is used
func (o *QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0) UnmarshalBinary(b []byte) error {
	var res QueryDenomMetadataByQueryStringOKBodyMetadataDenomUnitsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
