// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQueryDenomMetadataParams creates a new QueryDenomMetadataParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryDenomMetadataParams() *QueryDenomMetadataParams {
	return &QueryDenomMetadataParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryDenomMetadataParamsWithTimeout creates a new QueryDenomMetadataParams object
// with the ability to set a timeout on a request.
func NewQueryDenomMetadataParamsWithTimeout(timeout time.Duration) *QueryDenomMetadataParams {
	return &QueryDenomMetadataParams{
		timeout: timeout,
	}
}

// NewQueryDenomMetadataParamsWithContext creates a new QueryDenomMetadataParams object
// with the ability to set a context for a request.
func NewQueryDenomMetadataParamsWithContext(ctx context.Context) *QueryDenomMetadataParams {
	return &QueryDenomMetadataParams{
		Context: ctx,
	}
}

// NewQueryDenomMetadataParamsWithHTTPClient creates a new QueryDenomMetadataParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryDenomMetadataParamsWithHTTPClient(client *http.Client) *QueryDenomMetadataParams {
	return &QueryDenomMetadataParams{
		HTTPClient: client,
	}
}

/*
QueryDenomMetadataParams contains all the parameters to send to the API endpoint

	for the query denom metadata operation.

	Typically these are written to a http.Request.
*/
type QueryDenomMetadataParams struct {

	/* Denom.

	   denom is the coin denom to query the metadata for.
	*/
	Denom string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query denom metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryDenomMetadataParams) WithDefaults() *QueryDenomMetadataParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query denom metadata params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryDenomMetadataParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query denom metadata params
func (o *QueryDenomMetadataParams) WithTimeout(timeout time.Duration) *QueryDenomMetadataParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query denom metadata params
func (o *QueryDenomMetadataParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query denom metadata params
func (o *QueryDenomMetadataParams) WithContext(ctx context.Context) *QueryDenomMetadataParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query denom metadata params
func (o *QueryDenomMetadataParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query denom metadata params
func (o *QueryDenomMetadataParams) WithHTTPClient(client *http.Client) *QueryDenomMetadataParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query denom metadata params
func (o *QueryDenomMetadataParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDenom adds the denom to the query denom metadata params
func (o *QueryDenomMetadataParams) WithDenom(denom string) *QueryDenomMetadataParams {
	o.SetDenom(denom)
	return o
}

// SetDenom adds the denom to the query denom metadata params
func (o *QueryDenomMetadataParams) SetDenom(denom string) {
	o.Denom = denom
}

// WriteToRequest writes these params to a swagger request
func (o *QueryDenomMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param denom
	if err := r.SetPathParam("denom", o.Denom); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
