// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQueryParamsParams creates a new QueryParamsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryParamsParams() *QueryParamsParams {
	return &QueryParamsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryParamsParamsWithTimeout creates a new QueryParamsParams object
// with the ability to set a timeout on a request.
func NewQueryParamsParamsWithTimeout(timeout time.Duration) *QueryParamsParams {
	return &QueryParamsParams{
		timeout: timeout,
	}
}

// NewQueryParamsParamsWithContext creates a new QueryParamsParams object
// with the ability to set a context for a request.
func NewQueryParamsParamsWithContext(ctx context.Context) *QueryParamsParams {
	return &QueryParamsParams{
		Context: ctx,
	}
}

// NewQueryParamsParamsWithHTTPClient creates a new QueryParamsParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryParamsParamsWithHTTPClient(client *http.Client) *QueryParamsParams {
	return &QueryParamsParams{
		HTTPClient: client,
	}
}

/*
QueryParamsParams contains all the parameters to send to the API endpoint

	for the query params operation.

	Typically these are written to a http.Request.
*/
type QueryParamsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryParamsParams) WithDefaults() *QueryParamsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query params params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryParamsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query params params
func (o *QueryParamsParams) WithTimeout(timeout time.Duration) *QueryParamsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query params params
func (o *QueryParamsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query params params
func (o *QueryParamsParams) WithContext(ctx context.Context) *QueryParamsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query params params
func (o *QueryParamsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query params params
func (o *QueryParamsParams) WithHTTPClient(client *http.Client) *QueryParamsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query params params
func (o *QueryParamsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *QueryParamsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
