// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QueryAllBalancesReader is a Reader for the QueryAllBalances structure.
type QueryAllBalancesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryAllBalancesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryAllBalancesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewQueryAllBalancesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewQueryAllBalancesOK creates a QueryAllBalancesOK with default headers values
func NewQueryAllBalancesOK() *QueryAllBalancesOK {
	return &QueryAllBalancesOK{}
}

/*
QueryAllBalancesOK describes a response with status code 200, with default header values.

A successful response.
*/
type QueryAllBalancesOK struct {
	Payload *QueryAllBalancesOKBody
}

// IsSuccess returns true when this query all balances o k response has a 2xx status code
func (o *QueryAllBalancesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this query all balances o k response has a 3xx status code
func (o *QueryAllBalancesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query all balances o k response has a 4xx status code
func (o *QueryAllBalancesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this query all balances o k response has a 5xx status code
func (o *QueryAllBalancesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this query all balances o k response a status code equal to that given
func (o *QueryAllBalancesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the query all balances o k response
func (o *QueryAllBalancesOK) Code() int {
	return 200
}

func (o *QueryAllBalancesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/bank/v1beta1/balances/{address}][%d] queryAllBalancesOK %s", 200, payload)
}

func (o *QueryAllBalancesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/bank/v1beta1/balances/{address}][%d] queryAllBalancesOK %s", 200, payload)
}

func (o *QueryAllBalancesOK) GetPayload() *QueryAllBalancesOKBody {
	return o.Payload
}

func (o *QueryAllBalancesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(QueryAllBalancesOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryAllBalancesDefault creates a QueryAllBalancesDefault with default headers values
func NewQueryAllBalancesDefault(code int) *QueryAllBalancesDefault {
	return &QueryAllBalancesDefault{
		_statusCode: code,
	}
}

/*
QueryAllBalancesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type QueryAllBalancesDefault struct {
	_statusCode int

	Payload *QueryAllBalancesDefaultBody
}

// IsSuccess returns true when this query all balances default response has a 2xx status code
func (o *QueryAllBalancesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this query all balances default response has a 3xx status code
func (o *QueryAllBalancesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this query all balances default response has a 4xx status code
func (o *QueryAllBalancesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this query all balances default response has a 5xx status code
func (o *QueryAllBalancesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this query all balances default response a status code equal to that given
func (o *QueryAllBalancesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the query all balances default response
func (o *QueryAllBalancesDefault) Code() int {
	return o._statusCode
}

func (o *QueryAllBalancesDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/bank/v1beta1/balances/{address}][%d] Query_AllBalances default %s", o._statusCode, payload)
}

func (o *QueryAllBalancesDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /cosmos/bank/v1beta1/balances/{address}][%d] Query_AllBalances default %s", o._statusCode, payload)
}

func (o *QueryAllBalancesDefault) GetPayload() *QueryAllBalancesDefaultBody {
	return o.Payload
}

func (o *QueryAllBalancesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(QueryAllBalancesDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
QueryAllBalancesDefaultBody query all balances default body
swagger:model QueryAllBalancesDefaultBody
*/
type QueryAllBalancesDefaultBody struct {

	// code
	Code int32 `json:"code,omitempty"`

	// details
	Details []*QueryAllBalancesDefaultBodyDetailsItems0 `json:"details"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this query all balances default body
func (o *QueryAllBalancesDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryAllBalancesDefaultBody) validateDetails(formats strfmt.Registry) error {
	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Query_AllBalances default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Query_AllBalances default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this query all balances default body based on the context it is used
func (o *QueryAllBalancesDefaultBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryAllBalancesDefaultBody) contextValidateDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Details); i++ {

		if o.Details[i] != nil {

			if swag.IsZero(o.Details[i]) { // not required
				return nil
			}

			if err := o.Details[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Query_AllBalances default" + "." + "details" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Query_AllBalances default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *QueryAllBalancesDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryAllBalancesDefaultBody) UnmarshalBinary(b []byte) error {
	var res QueryAllBalancesDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
QueryAllBalancesDefaultBodyDetailsItems0 query all balances default body details items0
swagger:model QueryAllBalancesDefaultBodyDetailsItems0
*/
type QueryAllBalancesDefaultBodyDetailsItems0 struct {

	// at type
	AtType string `json:"@type,omitempty"`

	// query all balances default body details items0
	QueryAllBalancesDefaultBodyDetailsItems0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (o *QueryAllBalancesDefaultBodyDetailsItems0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv QueryAllBalancesDefaultBodyDetailsItems0

	rcv.AtType = stage1.AtType
	*o = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "@type")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		o.QueryAllBalancesDefaultBodyDetailsItems0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (o QueryAllBalancesDefaultBodyDetailsItems0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// at type
		AtType string `json:"@type,omitempty"`
	}

	stage1.AtType = o.AtType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(o.QueryAllBalancesDefaultBodyDetailsItems0) == 0 { // no additional properties
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(o.QueryAllBalancesDefaultBodyDetailsItems0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 { // "{}": only additional properties
		return additional, nil
	}

	// concatenate the 2 objects
	return swag.ConcatJSON(props, additional), nil
}

// Validate validates this query all balances default body details items0
func (o *QueryAllBalancesDefaultBodyDetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query all balances default body details items0 based on context it is used
func (o *QueryAllBalancesDefaultBodyDetailsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryAllBalancesDefaultBodyDetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryAllBalancesDefaultBodyDetailsItems0) UnmarshalBinary(b []byte) error {
	var res QueryAllBalancesDefaultBodyDetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
QueryAllBalancesOKBody query all balances o k body
swagger:model QueryAllBalancesOKBody
*/
type QueryAllBalancesOKBody struct {

	// balances
	Balances []*QueryAllBalancesOKBodyBalancesItems0 `json:"balances"`

	// pagination
	Pagination *QueryAllBalancesOKBodyPagination `json:"pagination,omitempty"`
}

// Validate validates this query all balances o k body
func (o *QueryAllBalancesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBalances(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePagination(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryAllBalancesOKBody) validateBalances(formats strfmt.Registry) error {
	if swag.IsZero(o.Balances) { // not required
		return nil
	}

	for i := 0; i < len(o.Balances); i++ {
		if swag.IsZero(o.Balances[i]) { // not required
			continue
		}

		if o.Balances[i] != nil {
			if err := o.Balances[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("queryAllBalancesOK" + "." + "balances" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("queryAllBalancesOK" + "." + "balances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *QueryAllBalancesOKBody) validatePagination(formats strfmt.Registry) error {
	if swag.IsZero(o.Pagination) { // not required
		return nil
	}

	if o.Pagination != nil {
		if err := o.Pagination.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("queryAllBalancesOK" + "." + "pagination")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("queryAllBalancesOK" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this query all balances o k body based on the context it is used
func (o *QueryAllBalancesOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateBalances(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidatePagination(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *QueryAllBalancesOKBody) contextValidateBalances(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Balances); i++ {

		if o.Balances[i] != nil {

			if swag.IsZero(o.Balances[i]) { // not required
				return nil
			}

			if err := o.Balances[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("queryAllBalancesOK" + "." + "balances" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("queryAllBalancesOK" + "." + "balances" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *QueryAllBalancesOKBody) contextValidatePagination(ctx context.Context, formats strfmt.Registry) error {

	if o.Pagination != nil {

		if swag.IsZero(o.Pagination) { // not required
			return nil
		}

		if err := o.Pagination.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("queryAllBalancesOK" + "." + "pagination")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("queryAllBalancesOK" + "." + "pagination")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *QueryAllBalancesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryAllBalancesOKBody) UnmarshalBinary(b []byte) error {
	var res QueryAllBalancesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
QueryAllBalancesOKBodyBalancesItems0 query all balances o k body balances items0
swagger:model QueryAllBalancesOKBodyBalancesItems0
*/
type QueryAllBalancesOKBodyBalancesItems0 struct {

	// amount
	Amount string `json:"amount,omitempty"`

	// denom
	Denom string `json:"denom,omitempty"`
}

// Validate validates this query all balances o k body balances items0
func (o *QueryAllBalancesOKBodyBalancesItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query all balances o k body balances items0 based on context it is used
func (o *QueryAllBalancesOKBodyBalancesItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryAllBalancesOKBodyBalancesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryAllBalancesOKBodyBalancesItems0) UnmarshalBinary(b []byte) error {
	var res QueryAllBalancesOKBodyBalancesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
QueryAllBalancesOKBodyPagination query all balances o k body pagination
swagger:model QueryAllBalancesOKBodyPagination
*/
type QueryAllBalancesOKBodyPagination struct {

	// next key
	// Format: byte
	NextKey strfmt.Base64 `json:"next_key,omitempty"`

	// total
	Total string `json:"total,omitempty"`
}

// Validate validates this query all balances o k body pagination
func (o *QueryAllBalancesOKBodyPagination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this query all balances o k body pagination based on context it is used
func (o *QueryAllBalancesOKBodyPagination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *QueryAllBalancesOKBodyPagination) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *QueryAllBalancesOKBodyPagination) UnmarshalBinary(b []byte) error {
	var res QueryAllBalancesOKBodyPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
