// Code generated by go-swagger; DO NOT EDIT.

package query

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewQueryDenomOwnersParams creates a new QueryDenomOwnersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryDenomOwnersParams() *QueryDenomOwnersParams {
	return &QueryDenomOwnersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryDenomOwnersParamsWithTimeout creates a new QueryDenomOwnersParams object
// with the ability to set a timeout on a request.
func NewQueryDenomOwnersParamsWithTimeout(timeout time.Duration) *QueryDenomOwnersParams {
	return &QueryDenomOwnersParams{
		timeout: timeout,
	}
}

// NewQueryDenomOwnersParamsWithContext creates a new QueryDenomOwnersParams object
// with the ability to set a context for a request.
func NewQueryDenomOwnersParamsWithContext(ctx context.Context) *QueryDenomOwnersParams {
	return &QueryDenomOwnersParams{
		Context: ctx,
	}
}

// NewQueryDenomOwnersParamsWithHTTPClient creates a new QueryDenomOwnersParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryDenomOwnersParamsWithHTTPClient(client *http.Client) *QueryDenomOwnersParams {
	return &QueryDenomOwnersParams{
		HTTPClient: client,
	}
}

/*
QueryDenomOwnersParams contains all the parameters to send to the API endpoint

	for the query denom owners operation.

	Typically these are written to a http.Request.
*/
type QueryDenomOwnersParams struct {

	/* Denom.

	   denom defines the coin denomination to query all account holders for.
	*/
	Denom string

	// PaginationCountTotal.
	PaginationCountTotal *bool

	// PaginationKey.
	//
	// Format: byte
	PaginationKey *strfmt.Base64

	// PaginationLimit.
	//
	// Format: uint64
	PaginationLimit *string

	// PaginationOffset.
	//
	// Format: uint64
	PaginationOffset *string

	// PaginationReverse.
	PaginationReverse *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query denom owners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryDenomOwnersParams) WithDefaults() *QueryDenomOwnersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query denom owners params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryDenomOwnersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query denom owners params
func (o *QueryDenomOwnersParams) WithTimeout(timeout time.Duration) *QueryDenomOwnersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query denom owners params
func (o *QueryDenomOwnersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query denom owners params
func (o *QueryDenomOwnersParams) WithContext(ctx context.Context) *QueryDenomOwnersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query denom owners params
func (o *QueryDenomOwnersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query denom owners params
func (o *QueryDenomOwnersParams) WithHTTPClient(client *http.Client) *QueryDenomOwnersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query denom owners params
func (o *QueryDenomOwnersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDenom adds the denom to the query denom owners params
func (o *QueryDenomOwnersParams) WithDenom(denom string) *QueryDenomOwnersParams {
	o.SetDenom(denom)
	return o
}

// SetDenom adds the denom to the query denom owners params
func (o *QueryDenomOwnersParams) SetDenom(denom string) {
	o.Denom = denom
}

// WithPaginationCountTotal adds the paginationCountTotal to the query denom owners params
func (o *QueryDenomOwnersParams) WithPaginationCountTotal(paginationCountTotal *bool) *QueryDenomOwnersParams {
	o.SetPaginationCountTotal(paginationCountTotal)
	return o
}

// SetPaginationCountTotal adds the paginationCountTotal to the query denom owners params
func (o *QueryDenomOwnersParams) SetPaginationCountTotal(paginationCountTotal *bool) {
	o.PaginationCountTotal = paginationCountTotal
}

// WithPaginationKey adds the paginationKey to the query denom owners params
func (o *QueryDenomOwnersParams) WithPaginationKey(paginationKey *strfmt.Base64) *QueryDenomOwnersParams {
	o.SetPaginationKey(paginationKey)
	return o
}

// SetPaginationKey adds the paginationKey to the query denom owners params
func (o *QueryDenomOwnersParams) SetPaginationKey(paginationKey *strfmt.Base64) {
	o.PaginationKey = paginationKey
}

// WithPaginationLimit adds the paginationLimit to the query denom owners params
func (o *QueryDenomOwnersParams) WithPaginationLimit(paginationLimit *string) *QueryDenomOwnersParams {
	o.SetPaginationLimit(paginationLimit)
	return o
}

// SetPaginationLimit adds the paginationLimit to the query denom owners params
func (o *QueryDenomOwnersParams) SetPaginationLimit(paginationLimit *string) {
	o.PaginationLimit = paginationLimit
}

// WithPaginationOffset adds the paginationOffset to the query denom owners params
func (o *QueryDenomOwnersParams) WithPaginationOffset(paginationOffset *string) *QueryDenomOwnersParams {
	o.SetPaginationOffset(paginationOffset)
	return o
}

// SetPaginationOffset adds the paginationOffset to the query denom owners params
func (o *QueryDenomOwnersParams) SetPaginationOffset(paginationOffset *string) {
	o.PaginationOffset = paginationOffset
}

// WithPaginationReverse adds the paginationReverse to the query denom owners params
func (o *QueryDenomOwnersParams) WithPaginationReverse(paginationReverse *bool) *QueryDenomOwnersParams {
	o.SetPaginationReverse(paginationReverse)
	return o
}

// SetPaginationReverse adds the paginationReverse to the query denom owners params
func (o *QueryDenomOwnersParams) SetPaginationReverse(paginationReverse *bool) {
	o.PaginationReverse = paginationReverse
}

// WriteToRequest writes these params to a swagger request
func (o *QueryDenomOwnersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param denom
	if err := r.SetPathParam("denom", o.Denom); err != nil {
		return err
	}

	if o.PaginationCountTotal != nil {

		// query param pagination.count_total
		var qrPaginationCountTotal bool

		if o.PaginationCountTotal != nil {
			qrPaginationCountTotal = *o.PaginationCountTotal
		}
		qPaginationCountTotal := swag.FormatBool(qrPaginationCountTotal)
		if qPaginationCountTotal != "" {

			if err := r.SetQueryParam("pagination.count_total", qPaginationCountTotal); err != nil {
				return err
			}
		}
	}

	if o.PaginationKey != nil {

		// query param pagination.key
		var qrPaginationKey strfmt.Base64

		if o.PaginationKey != nil {
			qrPaginationKey = *o.PaginationKey
		}
		qPaginationKey := qrPaginationKey.String()
		if qPaginationKey != "" {

			if err := r.SetQueryParam("pagination.key", qPaginationKey); err != nil {
				return err
			}
		}
	}

	if o.PaginationLimit != nil {

		// query param pagination.limit
		var qrPaginationLimit string

		if o.PaginationLimit != nil {
			qrPaginationLimit = *o.PaginationLimit
		}
		qPaginationLimit := qrPaginationLimit
		if qPaginationLimit != "" {

			if err := r.SetQueryParam("pagination.limit", qPaginationLimit); err != nil {
				return err
			}
		}
	}

	if o.PaginationOffset != nil {

		// query param pagination.offset
		var qrPaginationOffset string

		if o.PaginationOffset != nil {
			qrPaginationOffset = *o.PaginationOffset
		}
		qPaginationOffset := qrPaginationOffset
		if qPaginationOffset != "" {

			if err := r.SetQueryParam("pagination.offset", qPaginationOffset); err != nil {
				return err
			}
		}
	}

	if o.PaginationReverse != nil {

		// query param pagination.reverse
		var qrPaginationReverse bool

		if o.PaginationReverse != nil {
			qrPaginationReverse = *o.PaginationReverse
		}
		qPaginationReverse := swag.FormatBool(qrPaginationReverse)
		if qPaginationReverse != "" {

			if err := r.SetQueryParam("pagination.reverse", qPaginationReverse); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
